//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KirJemBankingEntities : DbContext
    {
        public KirJemBankingEntities()
            : base("name=KirJemBankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Charge> Charges { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }

        public System.Data.Entity.DbSet<BankingWebApplication.Models.DepositViewModel> Deposits { get; set; }
    }
}
